### ISSUE TITLE
Parts needed for crafting is more complicated than just tier

### ISSUE THREAD

**Issue by Yossi** [Toni-SM/cw_guild_bot#1]
I brute forced this info out of @cwcraftsbot
Here is the end result:

```python
        for n in range(1,103):
            if 1 <= n <= 18 or 59 <= n <= 61:
                parts_needed = 3
            elif 100 <= n <= 102:
                parts_needed = 4
            elif 19 <= n <= 58 or n in (91, 96, 97):
                parts_needed = 5
            elif 78 <= n <= 90 or 92 <= n <= 95 or n in (98, 99):
                parts_needed = 6
            elif 62 <= n <= 77:
                parts_needed = 0

            id = f'{n:02}'
```

**Comment by Toni-SM** [comment]
Thanks by the feedback. Some peoples in my guild said me about it. The cloak equipment needs less parts. I am going to update this project soon

**Comment by Toni-SM** [comment]
Now the amount of parts is done....

**Comment by Yossi** [comment]
The improved code still incorrectly reports 6 parts instead of 5 for the following weapons:

91 Griffin Knife
96 Meteor Bow
97 Nightfall Bow

**Comment by Toni-SM** [comment]
Thanks again for the feedback. Now the amount of parts is completed... I hope :)
